### ISSUE TITLE
Error message on order 4000-50636

### ISSUE THREAD

**Issue by carlahawley** [BrianRoyal/CNR2Automation#10]
![image](https://user-images.githubusercontent.com/29131924/27560369-880181dc-5a89-11e7-856c-532f5d23db73.png)

Error message when trying to edit order in R2 ticket entry

**Comment by techdotcom** [comment]
Looking into this

**Comment by techdotcom** [comment]
This should be fixed now.  I was able to recreate then after applying the fix was able to edit the line without the error.  
Updated process to set default lot as UNKNOWN when creating orders from store.
