### ISSUE TITLE
Price rule is not applied to item on PO

### ISSUE THREAD

**Issue by carlahawley** [BrianRoyal/CNR2Automation#13]
Price rule is not applied to item 5019111 on the order when coming across from the store server PO...  I can modify the order by changing the 
![image](https://user-images.githubusercontent.com/29131924/27609636-19a4c4b0-5b51-11e7-8ec3-56a8a0cd8267.png)
If I choose either one of these then the price rule takes effect.  It just doesn't come across and the price rule is applied.  I have the rule to ignore pricing on both Case of 8 and Box of 8
![image](https://user-images.githubusercontent.com/29131924/27609728-6c12753a-5b51-11e7-9854-2ad07b2b3c1f.png)

**Comment by techdotcom** [comment]
Most likely the price rules routine was disabled at the time this was run.  I did an order and the price rules seem to be applying as expected now.   Retest to confirm.
