### ISSUE TITLE
Logging In

### ISSUE THREAD

**Issue by kimber39** [BrianRoyal/CNR2Automation#2]
Hello All! I know that Carla is going to get Matt W. to get us access to the 144 Retail server. I tried to get into the 143 server under the company UAT-R2, using my id and password that I use for wholesale company and it's an invalid login. Thanks!

Kim

**Comment by BrianRoyal** [comment]
Hi Kim - a few things.  (1) we've installed UAT_MS on the 143 server as well.  (2) UAT-R2 might be using an old password.  What is your userID in CP?  I can reset the password so you can create a new one.

**Comment by kimber39** [comment]
Hi Brian,

My user ID is KIMF. Let me know when I can get in ☺!

**Comment by BrianRoyal** [comment]
Kim - you should be good to go.  Login with the user KIMF and just leave the password blank.  It should prompt you to set a new password.  I cleared your password history on the UAT database, so you're free to use the same password you use normally.  Thanks!  Brian
