### ISSUE TITLE
Unable to Edit 4025 Tickets

### ISSUE THREAD

**Issue by sjohnson17** [BrianRoyal/CNR2Automation#3]
Good Evening, 

I am unable to edit Document 4025-000606 and 4025-000611 in R2-CP Ticket Entry. When selecting 'Edit', the 'Process Order' is still displayed, keeping me from editing the purchase order. Normally, the display clears and the 'save' button appears for me to select after completing the ticket. 

You are welcome to call to clarify. Thank you!

**Comment by BrianRoyal** [comment]
Hi Sonja - we'll check this out and update this issue.
Thanks!
Brian

**Comment by BrianRoyal** [comment]
Sonja,
This appears to be a valid order in the live, production system.  Not part of the R2 Automation test project.

Please use GitHub for issues pertaining to the User Acceptance Testing of R2 Automation.  Use the normal process (email support@completenutrition.com) for all issues with the normal system.

Thanks!
Brian
