### ISSUE TITLE
Change Request: Don't cancel POs for backordered items in 943/944 track

### ISSUE THREAD

**Issue by BrianRoyal** [BrianRoyal/CNR2Automation#6]
This applies only to orders generated by R2 in the 943/944 track.
If an order is created and only partially reported as received by XPO, don't cancel the rest of the PO.  Assume the rest will come and leave the PO open.

For the 940/945 track, continue to cancel any remaining items that didn't get reported as shipped on the 945.

**Comment by techdotcom** [comment]
After checking things it appears that the 943/944 track operates as described.   I altered the X_MOCK_AS2_SERVICE to allow partial shipment simulation.  Running it with a parameter will set the qty recieved in the 944 to the value specified.  For example  "EXEC X_MOCK_AS2_SERVICE 50" will simulate XPO shipping a qty of 50 for each line item on the PO being processed.  This is in UAT and ready to use as needed.
