### ISSUE TITLE
Error: Item is inactive

### ISSUE THREAD

**Issue by kimber39** [BrianRoyal/CNR2Automation#7]
Item # 1001011 is active in wholesale and the hub, but is showing an error as item is inactive. 
Posted PO# 4005-P51351 and got error, Event Number: E4005103920 Processing complete. 1 transaction(s) had errors and were not processed.

*Tried to create another PO, #4001-51070 and got the same error as above, event number E400102264.

**Comment by techdotcom** [comment]
Cameron confirmed with Carla that all items available in production should now be available in UAT.
